In [2]:
import numpy as np

In [3]:
np.array([1,3,4],dtype='float')

array([1., 3., 4.])

In [5]:
np.ones([4,5])  

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.random.random((4,5))

array([[0.08007242, 0.39341574, 0.63578996, 0.22329923, 0.96782597],
       [0.07959338, 0.44451832, 0.43036383, 0.43775382, 0.13205373],
       [0.23579001, 0.84030476, 0.88954595, 0.374708  , 0.01865416],
       [0.18931124, 0.94399805, 0.33389808, 0.93955387, 0.43034969]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.seed(0)
x3 = np.random.randint(10,size=(3,4,5))

In [17]:
x3

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [19]:
print(x3[2, :,4])

[7 0 6 9]


In [20]:
## reverse all the list 
print(x3[::-1])

[[[9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]
  [8 4 1 4 9]]

 [[5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]
  [3 3 7 0 1]]

 [[5 0 3 3 7]
  [9 3 5 2 4]
  [7 6 8 8 1]
  [6 7 7 8 1]]]


In [21]:
a = [1,2]
b = a[1]

In [22]:
b = 4
print(a)
print(b)

[1, 2]
4


In [24]:
a = np.array([1,2]) #np array
a

array([1, 2])

In [25]:
b=a[1]
b

2

In [26]:
b = 4
print(a)
print(b)

[1 2]
4
